<?php

namespace HillsModeling\FrontEndBundle\Repository;

/**
 * TransitionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransitionsRepository extends \Doctrine\ORM\EntityRepository
{
}
